<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SlideinaCalendar.Shell</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SlideinaCalendar.Core\SlideinaCalendar.Core.csproj" />
  </ItemGroup>

</Project>
