<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SlideinaCalendar.Presentation</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SlideinaCalendar.Core\SlideinaCalendar.Core.csproj" />
    <ProjectReference Include="..\SlideinaCalendar.Data\SlideinaCalendar.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SlideinaCalendar.Presentation.Tests" />
  </ItemGroup>

</Project>
